# Generated by Django 4.2.29 on 2026-04-22 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp used for tracking age, expiry, and cleanup of pending signups.'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(help_text='Email address waiting for verification before account creation.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='hashed_password',
            field=models.CharField(help_text='Hashed password stored temporarily until verification is complete.', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', help_text='Intended role for the account being verified.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token used to verify and activate the pending account.', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Staff or admin employee identifier for institutional tracking.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_class_rep',
            field=models.BooleanField(default=False, help_text='Marks whether a student serves as a class representative.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Latest recorded activity timestamp for simple presence tracking.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Student registration number, used when the account belongs to a student.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', help_text='High-level account role used for access decisions in the platform.', max_length=10),
        ),
    ]
