# Generated by Django 4.2.29 on 2026-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
