# Generated by Django 4.2.29 on 2026-04-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_notifications', '0002_alter_comment_options_notification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
