#reports/models.py
"""
Module: reports
Author: Tipeii

Defines the database tables used to store analytical data. Instead of calculating heavy math every time a user loads the dashboard, we save historical snapshots here to make the system faster.
"""
from django.db import models
from django.conf import settings


class ReportSnapshot(models.Model):
    """
        Stores flexible, one-off reports generated by users. We use a JSON field here so we can dump different types of data without needing to change the database schema every time we invent a new report format.
        """
    REPORT_TYPES = (
        ('task_completion', 'Task Completion Rates'),
        ('student_performance', 'Student Performance'),
        ('system_usage', 'System Usage Stats'),
    )

    title = models.CharField(max_length=200)
    report_type = models.CharField(max_length=50, choices=REPORT_TYPES)
    data = models.JSONField()
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} - {self.created_at.strftime('%Y-%m-%d')}"


class UnitPerformanceSnapshot(models.Model):
    """
        Keeps a historical record of how a unit is doing. We use an append-only design here, meaning we never update a row, we just add a new one. This allows the frontend to draw trend lines over time.
        """

    SNAPSHOT_TYPES = (
        ('progress', 'Progress (In-Period)'),
        ('final', 'Final (Post-Deadline)'),
    )

    # Identifiers (Decoupled)
    unit_id = models.PositiveIntegerField(db_index=True)
    lecturer_id = models.PositiveIntegerField(db_index=True)

    # Metrics
    submission_rate = models.DecimalField(max_digits=5, decimal_places=2)
    on_time_ratio = models.DecimalField(max_digits=5, decimal_places=2)
    pending_reviews = models.PositiveIntegerField()
    overdue_feedback = models.PositiveIntegerField()

    # Logic Tracking
    snapshot_type = models.CharField(
        max_length=10,
        choices=SNAPSHOT_TYPES,
        default='progress'
    )
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-timestamp']
        # No UniqueConstraint on unit_id alone because we WANT multiple
        # rows over time to build the history for the AI.

    def __str__(self):
        return f"Unit {self.unit_id} - {self.snapshot_type} @ {self.timestamp.date()}"