# Generated by Django 4.2.29 on 2026-04-14 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0004_unit_description_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectured_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
