# Generated by Django 4.2.29 on 2026-04-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField(db_index=True)),
                ('lecturer_id', models.PositiveIntegerField(db_index=True)),
                ('submission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('on_time_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pending_reviews', models.PositiveIntegerField()),
                ('overdue_feedback', models.PositiveIntegerField()),
                ('snapshot_type', models.CharField(choices=[('progress', 'Progress (In-Period)'), ('final', 'Final (Post-Deadline)')], default='progress', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('task_completion', 'Task Completion Rates'), ('student_performance', 'Student Performance'), ('system_usage', 'System Usage Stats')], max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
