# Generated by Django 4.2.29 on 2026-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_unit_description_studygroup'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='study_groups',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='academic.studygroup'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submission_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
