name: Django CI

# This tells GitHub to run the tests when code goes to dev or main
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Grab your code
    - uses: actions/checkout@v4
    
    # 2. Install Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    # 3. Install Django using the file you just made
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # 4. Run the exact test command we just used locally!
    - name: Run Automated Tests
      run: |
        python manage.py test
